on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.cluster014.ovh.net
        username: gstart
        password: ${{ secrets.ftp_password }}
        local-dir: ./public/
        server-dir: /home/gstart/test-deploy-github/